name = "Dagology"
uuid = "cf4e94f3-7fee-4db9-9ef7-a4eaab5daac4"
authors = ["Enrico Caprioglio <enricocaprioglio@yahoo.com>"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
